name: Pacscript Request
description: Use this template to request the creation of a new Pacscript.
title: "PacReq: name_of_the_package"
labels: ["package request"]
body:
  - type: input
    id: package_name
    attributes:
      label: Package name
      description: Enter the package name
      value: "package"
    validations:
      required: true

  - type: checkboxes
    id: type
    attributes:
      label: Types
      description: Select the types of pacscripts you're requesting
      options:
        - label: -bin (Binary release of the package)
        - label: -git (Compiled off of the latest commit of the package)
        - label: -app (Appimage of the package)
        - label: nosuffix (Compiled off of the released source code)
        - label: -deb (Debian archive release of the package)

  - type: checkboxes
    id: architectures
    attributes:
      label: Architectures
      description: Select the architectures
      options:
        - label: any/all
        - label: amd64
        - label: arm64
        - label: armel
        - label: armhf
        - label: i386
        - label: mips64el
        - label: ppc64el
        - label: riscv64
        - label: s390x
    validations:
      required: false

  - type: input
    id: repology_reference
    attributes:
      label: Repology reference
      description: Enter the repology reference
    validations:
      required: false

  - type: input
    id: upstream_package_version
    attributes:
      label: Upstream package version
      description: Enter the upstream package version
      value: "1.0.0"
    validations:
      required: true

  - type: input
    id: package_release_version
    attributes:
      label: Package release version
      description: Enter the package release version
      value: "1"
    validations:
      required: false

  - type: input
    id: homepage_url
    attributes:
      label: Homepage URL
      description: Enter the homepage URL
    validations:
      required: false

  - type: input
    id: source_urls
    attributes:
      label: Source URLs
      description: Enter the source URLs (comma-separated)
      value: "https://website.com"
    validations:
      required: true

  - type: dropdown
    id: checksum_type
    attributes:
      label: Checksum Type
      description: Select the type of checksum
      options:
        - sha256
        - sha512
        - sha384
        - sha224
        - sha1
        - md5
        - b2
    validations:
      required: true

  - type: input
    id: checksums
    attributes:
      label: Checksums
      description: Enter the checksums (comma-separated)
      value: "SKIP"
    validations:
      required: true

  - type: input
    id: runtime_dependencies
    attributes:
      label: Runtime dependencies
      description: Enter the runtime dependencies (comma-separated)
    validations:
      required: false

  - type: input
    id: build_time_dependencies
    attributes:
      label: Build-time dependencies
      description: Enter the build-time dependencies (comma-separated)
    validations:
      required: false

  - type: input
    id: testing_dependencies
    attributes:
      label: Testing dependencies
      description: Enter the testing dependencies (comma-separated)
    validations:
      required: false

  - type: input
    id: optional_dependencies
    attributes:
      label: Optional dependencies
      description: Enter the optional dependencies (comma-separated)
    validations:
      required: false

  - type: textarea
    id: package_description
    attributes:
      label: Package description
      description: Enter the package description
      value: "A short description"
    validations:
      required: true

  - type: input
    id: license
    attributes:
      label: License
      description: Enter the license
      value: "LGPL-2.1-or-later"
    validations:
      required: false

  - type: input
    id: maintainer
    attributes:
      label: Maintainer
      description: Enter the maintainer
      value: "Person <place@thing.com>"
    validations:
      required: true

  - type: textarea
    id: building
    attributes:
      label: Building guide
      description: Provide the link to the building guide
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else you want to tell us about
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any additional information or special instructions
    validations:
      required: false
