name: Pacscript Request
description: "Use this template to request the creation of a new Pacscript."
title: "PacReq: name_of_the_package"
labels: ["package request"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the type of pacscript you're requesting
      options:
        - -bin (Binary release of the package)
        - -git (Compiled off of the latest commit of the package)
        - -app (Appimage of the package)
        - -deb (Debian achieve release of the package)
        - other/nosuffix (Compiled off of the released source code, etc.)
    validations:
      required: true

  - type: input
    id: package_name
    attributes:
      label: "Package name"
      description: "Enter the package name (e.g., foo-bin)"
      value: "foo-bin"
    validations:
      required: true

  - type: dropdown
    id: architectures
    attributes:
      label: "Architectures"
      description: "Select the architectures (leave blank for any/all)"
      multiple: true
      options:
        - "amd64"
        - "arm64"
        - "armel"
        - "armhf"
        - "i386"
        - "mips64el"
        - "ppc64el"
        - "riscv64"
        - "s390x"
    validations:
      required: false

  - type: input
    id: upstream_package_version
    attributes:
      label: "Latest package version"
      description: "Enter the most recent package version (e.g., 1.0.0)"
      value: "1.0.0"
    validations:
      required: true

  - type: input
    id: homepage_url
    attributes:
      label: "Homepage URL"
      description: "Enter the homepage URL (e.g., https://foo.com/bar)"
    validations:
      required: false

  - type: input
    id: source_urls
    attributes:
      label: "Source URLs"
      description: "Enter the source URLs (comma-separated, e.g., https://website.com)"
      value: "https://website.com/foo-bin.tar.xz"
    validations:
      required: true

  - type: dropdown
    id: checksum_type
    attributes:
      label: "Checksum Type"
      description: "Select the type of checksum"
      options:
        - "sha256"
        - "sha512"
        - "sha384"
        - "sha224"
        - "sha1"
        - "md5"
        - "b2"
    validations:
      required: true

  - type: input
    id: checksums
    attributes:
      label: "Checksums"
      description: "Enter the checksums (comma-separated, in matched order to source URLs; use 'SKIP' for -git or any not applicable)"
      value: "SKIP"
    validations:
      required: true

  - type: input
    id: runtime_dependencies
    attributes:
      label: "Dependencies"
      description: "Enter the runtime dependencies (comma-separated, e.g., dependency1, dependency2)"
    validations:
      required: false

  - type: input
    id: build_time_dependencies
    attributes:
      label: "Build Dependencies"
      description: "Enter the build-time dependencies (comma-separated, e.g., dependency1, dependency2)"
    validations:
      required: false

  - type: input
    id: testing_dependencies
    attributes:
      label: "Check Dependencies"
      description: "Enter the testing dependencies (comma-separated, e.g., dependency1, dependency2)"
    validations:
      required: false

  - type: input
    id: optional_dependencies
    attributes:
      label: "Optional Dependencies"
      description: "Enter the optional dependencies (comma-separated, format: pkg: description; e.g., dependency1: A brief description, dependency2: Another brief description)"
    validations:
      required: false

  - type: textarea
    id: package_description
    attributes:
      label: "Package Description"
      description: "Enter the package description (e.g., A short description)"
      value: "A short description"
    validations:
      required: true

  - type: input
    id: repology_reference
    attributes:
      label: "Repology reference"
      description: "Enter the repology reference (e.g., project: bar)"
    validations:
      required: false

  - type: input
    id: license
    attributes:
      label: "License"
      description: "Enter the license (e.g., LGPL-2.1-or-later)"
      value: "LGPL-2.1-or-later"
    validations:
      required: false

  - type: input
    id: maintainer
    attributes:
      label: "Maintainer"
      description: "Enter the maintainer (format: Name <email>, e.g., John Doe <john.doe@example.com>)"
      value: "Person <place@thing.com>"
    validations:
      required: true

  - type: textarea
    id: building
    attributes:
      label: "Building guide"
      description: "Provide the link to the building guide (e.g., https://foo.com/build-guide)"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional context"
      description: "Anything else you want to tell us about"
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Any additional information or special instructions"
    validations:
      required: false
