name: Check/Generate distrolist

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  gen-distrolist:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Generate distrolist
        run: |
          mapfile -t parsed_distros < <(curl -fsSL https://salsa.debian.org/debian/distro-info-data/-/raw/main/{ubuntu.csv,debian.csv} \
            | awk -F ',' -v current_date="$(date +'%Y-%m-%d')" '
              BEGIN {
                is_first = 1
              }
              $3 == "series" {
                if (is_first) {
                  print "ubuntu:"
                  is_first = 0
                } else {
                  print "  devel\ndebian:"
                }
                next
              }
              NR > 1 && (($6 > current_date) || ($7 > current_date) || ($6 == "")) &&
              ($4 <= current_date) && $3 != "experimental" {
                gsub(" LTS", "", $1);
                if ($1 != "") {
                  print "  " $3 "/" $1
                } else {
                  print "  " $3
                }
              }')
          printf "%s\n" "${parsed_distros[@]}" > distrolist

      - name: Calculate diff + PR title
        id: calc_pr
        run: |
          diff_output="$(git diff --unified=0 distrolist)"
          if [[ -z "${diff_output}" ]]; then
            echo "No changes to distrolist."
            echo "::set-output name=changes_detected::false"
            exit 0
          else
            echo "::set-output name=changes_detected::true"
          fi
          added_entries="$(echo "$diff_output" | grep '^+ ' | sed 's/^\+  //' | awk -v ORS=', ' '{print "`"$0"`"}' | sed 's/, $//')"
          removed_entries="$(echo "$diff_output" | grep '^- ' | sed 's/^-  //' | awk -v ORS=', ' '{print "`"$0"`"}' | sed 's/, $//')"
          title="upd(distrolist): "
          if [[ -n "$added_entries" && -z "$removed_entries" ]]; then
            title+="add ${added_entries}"
          elif [[ -z "$added_entries" && -n "$removed_entries" ]]; then
            title+="rm ${removed_entries}"
          elif [[ -n "$added_entries" && -n "$removed_entries" ]]; then
            title+="add ${added_entries}; rm ${removed_entries}"
          fi
          echo "distlist_title=${title}" >> $GITHUB_ENV
          echo "distlist_body=Automatically generated by CI" >> $GITHUB_ENV
          echo "dl_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create PR if changes detected
        if: steps.calc_pr.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-path: distrolist
          base: master
          branch: update-distrolist-${{ env.dl_date }}
          title: ${{ env.distlist_title }}
          body: ${{ env.distlist_body }}
