name: PPR Package Packer

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build'
        required: true
      distro:
        description: 'Distro to build on'
        required: true
        type: choice
        options:
          - debian-stable
          - debian-testing
          - debian-unstable
          - ubuntu-latest
          - ubuntu-rolling
          - ubuntu-devel
      architecture:
        description: 'Architecture to build on'
        required: true
        type: choice
        options:
          - amd64
          - arm64
          - all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Init
      uses: actions/checkout@v4

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Package
      run: |
        mkdir -p out && cd out
        ../scripts/packer.sh "${{ github.event.inputs.package }}" "${{ github.event.inputs.distro }}" "${{ github.event.inputs.architecture }}"
        debfile=(*.deb)
        echo "DEBNAME=${debfile}" >> $GITHUB_ENV

    - name: Upload .deb files
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DEBNAME }}
        path: out/${{ env.DEBNAME }}
