name: PPR Package Packer

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build'
        required: true
      distro:
        description: 'Distro to build on'
        required: true
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-rolling
          - ubuntu-devel
          - debian-stable
          - debian-testing
          - debian-unstable
      architecture:
        description: 'Architecture to build on'
        required: true
        type: choice
        options:
          - all
          - amd64
          - arm64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Init
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y jq rclone

    - name: Package
      run: |
        mkdir -p out && cd out
        ../scripts/packer.sh "${{ github.event.inputs.package }}" "${{ github.event.inputs.distro }}" "${{ github.event.inputs.architecture }}"
        debfile=(*.deb)
        echo "DEBNAME=${debfile}" >> $GITHUB_ENV

    - name: Upload .deb files
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DEBNAME }}
        path: out/${{ env.DEBNAME }}

    - name: Sync to repo
      run: |
        rclone config create backblaze b2 account ${{ secrets.B2_ID }} key ${{ secrets.B2_KEY }}
        rclone copy out/${{ env.DEBNAME }} backblaze:pacstall/${{ github.event.inputs.distro }}/${{ matrix.architecture }}/${{ env.DEBNAME }}
